statefulset:
  spec:
    template:
      spec:
        initContainers:
          db-migrate:
            image:
              repository: migrate/migrate
            command: ["sh", "-c", "until pg_isready -h db; do sleep 1; done"]
        containers:
          postgres:
            image:
              repository: postgres
              tag: "17.6"
    volumeClaimTemplates:
      data:
        mount:
          mountPath: "/var/lib/postgresql/data"
        spec:
          resources:
            requests:
              storage: 20Gi

service:
  spec:
    ports:
      tcp:
        port: 5432

secrets:
  envVars:
    data:
      POSTGRES_PASSWORD: postgres
