---
# Source: vault/templates/base.tpl
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.1.0
  name: vault
---
# Source: vault/templates/base.tpl
apiVersion: v1
kind: Secret
data:
  VAULT_DEV_ROOT_TOKEN_ID: cm9vdA==
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.1.0
  name: vault-env-vars
---
# Source: vault/templates/base.tpl
apiVersion: v1
kind: ConfigMap
data:
  ___vault___config.d___config.json: |
    {"disable_mlock":true,"storage":{"file":{"path":"/vault/file"}},"ui":true}
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.1.0
  name: vault-files
---
# Source: vault/templates/base.tpl
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.1.0
  name: vault-file
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Source: vault/templates/base.tpl
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.1.0
  name: vault
spec:
  ports:
  - name: http
    port: 8200
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
---
# Source: vault/templates/base.tpl
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.1.0
  name: vault
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: vault
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: vault
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: vault
        helm.sh/chart: vault-0.1.0
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: vault-env-vars
        image: hashicorp/vault:1.20.2
        name: vault
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /vault/config.d/config.json
          name: config-map-files
          readOnly: true
          subPath: ___vault___config.d___config.json
        - mountPath: /vault/file
          name: persistent-volume-claim-file
      serviceAccountName: vault
      volumes:
      - configMap:
          name: vault-files
        name: config-map-files
      - name: persistent-volume-claim-file
        persistentVolumeClaim:
          claimName: vault-file
---
# Source: vault/templates/base.tpl
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.1.0
  name: vault
spec:
  rules:
  - host: vault.example.local
    http:
      paths:
      - backend:
          service:
            name: vault
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - vault.example.local
    secretName: vault-tls-secret
---
# Source: vault/templates/base.tpl
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.1.0
  name: vault
spec:
  endpoints:
  - path: /sys/metrics
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: vault
      app.kubernetes.io/name: vault
