base:
  image:
    repository: hashicorp/vault
    pullPolicy: IfNotPresent
    tag: 1.20.2

  service:
    spec:
      ports:
        http:
          port: 8200

  ingress:
    spec:
      rules:
        "vault.example.local":
          http:
            paths:
              "/":
                backend:
                  service:
                    name: vault-base
                    port:
                      name: http
