image:
  repository: hashicorp/vault
  tag: 1.20.2

service:
  spec:
    ports:
      http:
        port: 8200

configMaps:
  files:
    data:
      "/vault/config.d/config.json":
        ui: true
        disable_mlock: true
        storage:
          file:
            path: /vault/file

secrets:
  envVars:
    data:
      VAULT_DEV_ROOT_TOKEN_ID: root

ingress:
  spec:
    rules:
      "vault.example.local":
        tls:
          secretName: vault-tls-secret
        http:
          paths:
            "/":
              backend:
                service: null

persistentVolumeClaims:
  file:
    spec:
      resources:
        requests:
          storage: 1Gi
    mount:
      mountPath: /vault/file

serviceMonitor:
  spec:
    endpoints:
      http:
        path: /sys/metrics
