deployment:
  spec:
    template:
      spec:
        volumes:
          tmp:
            emptyDir: {}
        containers:
          vault:
            volumeMounts:

            image:
              repository: hashicorp/vault
              tag: 1.20.3

service:
  spec:
    ports:
      http:
        port: 8200

configMaps:
  files:
    data:
      "/vault/config/config.json":
        ui: true
        disable_mlock: true

secrets:
  envVars:
    data:
      VAULT_DEV_ROOT_TOKEN_ID: root

ingress:
  spec:
    rules:
      "vault.example.local":
        tls:
          secretName: vault-tls-secret
        http:
          paths:
            "/":
              backend:
                service:
                  port:
                    name: http

serviceMonitor:
  spec:
    endpoints:
      http:
        path: /sys/metrics
