name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-go@v5.5.0
      - uses: pre-commit/action@v3.0.1
