name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: hiddenmarten/action-helm-chart-releaser@v1.0.3
        with:
          chart_path: base
          password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
